import { useArticle } from 'hooks/useArticle'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const articles = useArticle()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next with Newt</h1>
        {articles.map((a) => (
          <p key={a._id}>{a.title}</p>
        ))}
      </main>
    </div>
  )
}
